# Generated by Django 5.0.7 on 2025-11-01 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseonsiterequest',
            name='course',
        ),
        migrations.RemoveField(
            model_name='courseonsiterequest',
            name='user',
        ),
        migrations.RemoveField(
            model_name='courserecordedrequest',
            name='course',
        ),
        migrations.RemoveField(
            model_name='courserecordedrequest',
            name='user',
        ),
        migrations.RemoveField(
            model_name='toolrequest',
            name='tool',
        ),
        migrations.RemoveField(
            model_name='toolrequest',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userinteraction',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='userinteraction',
            name='user',
        ),
        migrations.DeleteModel(
            name='BookRequest',
        ),
        migrations.DeleteModel(
            name='CourseOnsiteRequest',
        ),
        migrations.DeleteModel(
            name='CourseRecordedRequest',
        ),
        migrations.DeleteModel(
            name='ToolRequest',
        ),
        migrations.DeleteModel(
            name='UserInteraction',
        ),
    ]
